### ISSUE TITLE
Exceptionally Bloated Front-End Development Experience on Clojure Stack with Garden

### ISSUE THREAD

**Issue by WorldsEndless** [noprompt/garden#130] opened 2017-03-20 15:26 UTC
My app has a Clojure stack with Reagent CLJS on the front and the excellent Garden for the CSS work. My laptop is running Linux with 8gb ram. Development life is good until I hit the styling stage; at that point, my environment looks like this: 

1. lein run ;; Get the back-end, db-interaction, and AJAX responses going. Instead I sometimes use cider-jack-in and mount.core/start
2. lein figwheel ;; for awesome CLJS work
3. lein garden auto ;; combines with figwheel for real-time CSS updates for CSS written in CLJ
4. My laptop chokes on the ram demands and essentially freezes to an unusable state. 

Note that I end up with 2-3 REPL/Lein processes running, which consumes all my resources. How can I loosen the arteries of this set-up so I can actually work on the CSS on my laptop? On my heftier 16gb desktop it's fine, but for front-end work I would really hope to be able to pull it off more easily. 

Cross-posted to the Luminus google group: https://groups.google.com/forum/#!topic/luminusweb/2S330szX0pI

**Comment by azizzaeny** [comment] 2017-03-21 17:28
hi @WorldsEndless ... 
did you try [boot](https://github.com/boot-clj/boot) ?

1. use [boot-figreload](https://github.com/boot-clj/boot-figreload/) from @arichiardi
2. use [boot-garden](https://github.com/martinklepsch/boot-garden) from @martinklepsch
3. or optionally trying atomic way with [boot-atomizer](https://github.com/azizzaeny/boot-atomizer)

**Comment by noprompt** [comment] 2017-03-22 21:59
This sounds like the problem is `lein` and not Garden. Closing until there's supporting evidence.

**Closed by noprompt** 2017-03-22 21:59 UTC
